const lessonData = {};

lessonData["01_CharlesPonzi.mp3"] = [{
    text: "1. Charles Ponzi. Charles Ponzi is one of the most famous thieves in history. His name is now used for a special kind of crime called a 'Ponzi scheme.' In the year 1920, he moved to America to find a better life. He told people he had a secret way to make them very rich, very fast. He promised to give them a lot of extra money in just 90 days. Many normal people gave him all their life savings because they wanted to be rich. But Ponzi did not have a real business. He lied to everyone. He just took money from the new people and gave it to the older investors. He used the rest of the money to buy nice suits, expensive shoes, and big houses for himself. People thought he was a genius businessman. Finally, a newspaper reporter investigated his business and found out the terrible truth. The police arrested him immediately, and his investors lost twenty million dollars. He went to a dark prison for many years. He eventually died a very poor man, but his criminal name is still famous all over the world today.",
    dict: { "thieves": "hırsızlar", "scheme": "plan/düzen", "promised": "söz verdi", "savings": "birikimler", "investors": "yatırımcılar", "genius": "dahi", "investigated": "araştırdı/soruşturdu", "terrible": "korkunç", "arrested": "tutukladı", "immediately": "hemen", "prison": "hapishane", "eventually": "sonunda" },
    questions: [ {q:"Was Charles Ponzi a famous thief?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he promise to make people rich very fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a real business?", a_en:"No", a_tr:"Hayır"}, {q:"Did he buy nice suits and expensive shoes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a newspaper reporter investigate him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the investors lose twenty million dollars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die a very rich man?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["02_VictorLustig.mp3"] = [{
    text: "2. Victor Lustig. Victor Lustig was a very clever and highly dangerous con man. In the year 1925, he read a newspaper article that said the famous Eiffel Tower in Paris needed very expensive repairs. He got an amazing and crazy idea. He made fake government papers and invited rich metal buyers to a secret hotel meeting. He told them the city was too poor and wanted to sell the Eiffel Tower for scrap metal! He was so polite, dressed so well, and spoke so confidently that one businessman believed his big lie. The man gave Lustig a huge suitcase completely full of cash. Lustig took the heavy money and quickly escaped on a train to Austria. The buyer was too embarrassed and ashamed to tell the police about his silly mistake. Lustig was so successful that he actually returned to Paris later and tried to sell the famous tower a second time! Eventually, the American police caught him for making fake money. A judge sent him to the famous island prison called Alcatraz. He died there, but people still tell stories about his incredible Eiffel Tower trick today.",
    dict: { "clever": "zeki", "con man": "dolandırıcı", "repairs": "tamiratlar", "fake": "sahte", "invited": "davet etti", "scrap metal": "hurda metal", "confidently": "kendinden emin", "suitcase": "bavul", "escaped": "kaçtı", "embarrassed": "utanmış", "ashamed": "mahçup/utanmış", "incredible": "inanılmaz" },
    questions: [ {q:"Was Victor Lustig a clever con man?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to sell the Eiffel Tower for scrap metal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a businessman give him a suitcase full of cash?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the buyer tell the police immediately?", a_en:"No", a_tr:"Hayır"}, {q:"Did Lustig try to sell the tower a second time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the American police catch him?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sent to Alcatraz prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_FrankAbagnaleJr.mp3"] = [{
    text: "3. Frank Abagnale Jr. Frank Abagnale Jr. started his long life of crime when he was just a young teenager. He ran away from his home and quickly realized he could trick people very easily. First, he pretended to be a real airplane pilot. He bought a fake pilot uniform and flew on big airplanes for free all over the world. Then, he decided to change his job. He pretended to be a smart doctor in a hospital and a serious lawyer in a courtroom. He had no education for these jobs. He was just very smart, confident, and a great actor, so everyone believed his lies. He also made millions of dollars by creating fake bank checks. He spent the stolen money on expensive food and nice hotels. The police chased him across many different countries for years. Finally, the police caught him hiding in France. After he spent time in a dark prison, the government gave him a special job. He started working for the police to help them catch other thieves. His crazy and exciting life story became a very famous movie called Catch Me If You Can.",
    dict: { "teenager": "genç/ergen", "pretended": "gibi davrandı", "pilot": "pilot", "uniform": "üniforma", "courtroom": "mahkeme salonu", "education": "eğitim", "actor": "aktör/oyuncu", "checks": "çekler (banka)", "chased": "kovaladı", "hiding": "saklanıyor", "thieves": "hırsızlar" },
    questions: [ {q:"Did Frank Abagnale start his crimes as a teenager?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pretend to be an airplane pilot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pretend to be a doctor and a lawyer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have real education for these jobs?", a_en:"No", a_tr:"Hayır"}, {q:"Did he make fake bank checks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police catch him in France?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he later start working for the police?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_AnnaSorokin.mp3"] = [{
    text: "4. Anna Sorokin. Anna Sorokin was a young woman from Russia, but she created a completely fake and glamorous life in New York City. She changed her name to Anna Delvey. She told everyone she was a very rich German woman who had millions of dollars in her family bank account. She wore very expensive designer clothes, lived in the best luxury hotels, and ate at the most famous restaurants. She was very good at acting like a rich, important, and busy person. She tricked her rich friends, big banks, and nice hotels to pay for her very expensive lifestyle. She even tried to get a twenty-two million dollar loan from a major bank to start a fake art club for rich people. Finally, her friends realized she never paid them back their money. The luxury hotels called the police because she did not pay her large room bills. The police arrested her in the year 2017, and a judge sent her to prison for her crimes. Her crazy story recently became a very popular television show that many people watched around the world.",
    dict: { "glamorous": "göz alıcı/büyüleyici", "designer clothes": "tasarımcı kıyafetleri", "lifestyle": "yaşam tarzı", "loan": "kredi/borç", "major": "büyük/ana", "realized": "fark etti", "bills": "faturalar/hesaplar", "arrested": "tutukladı", "crimes": "suçlar" },
    questions: [ {q:"Was Anna Sorokin really from Germany?", a_en:"No", a_tr:"Hayır"}, {q:"Did she create a fake and glamorous life in New York?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she live in the best luxury hotels?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she trick her friends and banks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she try to get a huge loan for an art club?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hotels call the police?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she sent to prison for her crimes?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_BernieMadoff.mp3"] = [{
    text: "5. Bernie Madoff. Bernie Madoff created the biggest and worst financial crime in world history. For many years, he was a very respected and famous businessman in New York. People trusted him completely because he seemed very honest, quiet, and successful. He promised people that if they gave him their money, he would invest it in the stock market and make them much richer. Thousands of people, including famous movie actors and big charities that help poor people, gave him their entire life savings. But Madoff did not invest the money. Just like Charles Ponzi, he used a fake system. He just used new money to pay the older investors. He stole about sixty-five billion dollars! In the year 2008, the world economy crashed badly. Too many people asked for their money back at the same time, and Madoff could not pay them. He finally told his two sons the terrible truth, and they immediately called the police. The judge was very angry and sent him to prison for one hundred and fifty years. He died in prison as a very hated man.",
    dict: { "financial": "finansal", "respected": "saygı duyulan", "trusted": "güvendi", "honest": "dürüst", "invest": "yatırım yapmak", "stock market": "borsa", "charities": "hayır kurumları", "economy": "ekonomi", "crashed": "çöktü", "terrible": "korkunç", "hated": "nefret edilen" },
    questions: [ {q:"Did Bernie Madoff create a massive financial crime?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people trust him because he seemed honest?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he really invest the money in the stock market?", a_en:"No", a_tr:"Hayır"}, {q:"Did he use new money to pay older investors?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the economy crash in 2008?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his two sons call the police?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sent to prison for one hundred and fifty years?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_ElizabethHolmes.mp3"] = [{
    text: "6. Elizabeth Holmes. Elizabeth Holmes was a young university student who left her school to start a new medical company called Theranos. She always wore black shirts and spoke in a strange, deep voice to sound very serious and smart. She told the world that her company invented a magic medical machine. She promised this small machine could test for hundreds of dangerous diseases using just one tiny drop of blood from a person's finger. Rich investors thought this invention would change the whole world, so they gave her billions of dollars. She became very famous and was on the cover of many important magazines. There was only one big problem: the machine did not work at all. It was completely fake. She lied to her rich investors, to smart doctors, and to sick patients who needed real help. Finally, a brave newspaper reporter discovered her dark secret and wrote a long article about her terrible lies. Her big company closed down quickly. A judge sent her to prison for eleven years because she put many sick people in serious danger to make herself rich and famous.",
    dict: { "medical": "tıbbi", "invented": "icat etti", "diseases": "hastalıklar", "drop": "damla", "blood": "kan", "investors": "yatırımcılar", "invention": "icat", "magazines": "dergiler", "patients": "hastalar", "reporter": "muhabir/gazeteci", "danger": "tehlike" },
    questions: [ {q:"Did Elizabeth Holmes start a medical company?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she say her machine needed a lot of blood?", a_en:"No", a_tr:"Hayır"}, {q:"Did rich investors give her billions of dollars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the magic medical machine actually work?", a_en:"No", a_tr:"Hayır"}, {q:"Did she lie to doctors and sick patients?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a newspaper reporter discover her secret?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she sent to prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_GregorMacGregor.mp3"] = [{
    text: "7. Gregor MacGregor. Gregor MacGregor was a Scottish soldier who created one of the most unbelievable and cruel lies in history. In the year 1821, he went back to Great Britain and told people he was the Prince of a new country called Poyais. He said Poyais was a beautiful, rich, and peaceful country in Central America. He showed people colorful drawings of beautiful cities, detailed maps, and even fake money for this perfect country. He said the weather was always warm and there was yellow gold everywhere in the rivers. Many British people believed his wonderful story and bought empty land from him. They packed their bags, left their homes, and sailed across the dangerous ocean to live in this amazing paradise. But when they finally arrived, there was no beautiful city. There was only a dark, wild, and dangerous jungle. The perfect country of Poyais did not exist at all! Most of the poor people got very sick and died in the jungle. MacGregor escaped with all their money and was never punished by the police for his terrible and deadly crime.",
    dict: { "unbelievable": "inanılmaz", "cruel": "zalim", "peaceful": "huzurlu", "drawings": "çizimler", "detailed": "detaylı", "empty": "boş", "sailed": "yelken açtılar", "paradise": "cennet", "jungle": "orman/balta girmemiş orman", "exist": "var olmak", "punished": "cezalandırıldı" },
    questions: [ {q:"Did MacGregor say he was the Prince of Poyais?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he show people fake money and maps?", a_en:"Yes", a_tr:"Evet"}, {q:"Did British people buy empty land from him?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there a beautiful city when they arrived?", a_en:"No", a_tr:"Hayır"}, {q:"Was Poyais just a dangerous jungle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did most of the poor people die in the jungle?", a_en:"Yes", a_tr:"Evet"}, {q:"Was MacGregor ever punished by the police?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["08_FerdinandWaldoDemara.mp3"] = [{
    text: "8. Ferdinand Waldo Demara. Ferdinand Waldo Demara was called 'The Great Impostor.' He was a strange man who loved to pretend to be other people. He did not usually want to steal money; he just wanted to feel very important and respected. Over his long life, he pretended to be a quiet monk, a tough prison guard, a smart university teacher, and a serious lawyer. His most famous trick happened during the difficult Korean War. He stole the identity of a real doctor and joined the Canadian Navy as a ship's surgeon. He had absolutely no medical training, but he read thick medical books very fast in his room. Amazingly, he actually did real, dangerous surgeries on badly injured soldiers and saved their lives! When the real doctor finally found out about the lie, the Navy sent Demara home immediately. The military leaders were too embarrassed to put him in jail because he actually helped the soldiers. He kept changing his name and his identity until he died. He lived a very lonely but exciting life, always pretending to be someone else.",
    dict: { "Impostor": "sahtekar/başkasının kılığına giren", "pretend": "gibi davranmak", "respected": "saygı duyulan", "monk": "keşiş", "guard": "gardiyan", "surgeon": "cerrah", "medical training": "tıbbi eğitim", "surgeries": "ameliyatlar", "injured": "yaralı", "embarrassed": "utanmış", "lonely": "yalnız" },
    questions: [ {q:"Was Demara called The Great Impostor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he usually want to steal money?", a_en:"No", a_tr:"Hayır"}, {q:"Did he pretend to be a prison guard and a lawyer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he join the Navy as a surgeon?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have real medical training?", a_en:"No", a_tr:"Hayır"}, {q:"Did he do real surgeries and save lives?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Navy put him in jail?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["09_GeorgeParker.mp3"] = [{
    text: "9. George Parker. George Parker was a very bold and confident con man who lived in New York City. From the 1880s to the 1920s, he made his living by selling famous public monuments to rich visitors. His absolute favorite thing to 'sell' was the beautiful and famous Brooklyn Bridge. He made very good fake government documents to prove he owned the huge bridge. He found rich tourists and sold the bridge to them for thousands of dollars. The tourists only realized it was a terrible trick when the city police stopped them from building ticket booths on the bridge! Parker also successfully 'sold' other very famous places, like Madison Square Garden and the huge Statue of Liberty. He was very charming, wore nice clothes, and spoke very well, so people easily believed his crazy stories. The police arrested him many different times over the years. He always tried to trick people again when he was free. Finally, a judge became very tired of his endless lies and sent him to prison for the rest of his life. He died behind bars, far from the bridge.",
    dict: { "bold": "cesur", "confident": "kendinden emin", "monuments": "anıtlar", "prove": "kanıtlamak", "tourists": "turistler", "ticket booths": "bilet gişeleri", "charming": "çekici", "arrested": "tutukladı", "endless": "bitmeyen", "behind bars": "demir parmaklıklar ardında" },
    questions: [ {q:"Was George Parker a confident con man?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell famous public monuments?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the Brooklyn Bridge his favorite thing to sell?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use fake government documents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did tourists try to build ticket booths on the bridge?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he also sell the Statue of Liberty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die a free man?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["10_SimonLeviev.mp3"] = [{
    text: "10. Simon Leviev. Simon Leviev is a modern con man who used the internet to steal a lot of money. His real name is Shimon Hayut. He used a popular dating app called Tinder to meet lonely women. He told them he was the rich son of a famous diamond billionaire. He took the women on expensive private airplanes and stayed in the best luxury hotels to prove he was very wealthy. After the women fell deeply in love with him, he started his cruel plan. He sent them scary pictures of his bodyguard with a bloody head. He told the women his dangerous enemies were attacking him and he could not use his own credit cards safely. He begged the women to borrow money to help save his life. The worried women took out huge bank loans to help the man they loved. He used their money to travel and find new victims to trick. He stole millions of dollars before the police finally caught him. His victims are still paying back the huge bank loans today, while he continues to live a free life.",
    dict: { "dating app": "arkadaşlık uygulaması", "lonely": "yalnız", "billionaire": "milyarder", "wealthy": "zengin", "cruel": "zalim", "scary": "korkutucu", "bodyguard": "koruma", "begged": "yalvardı", "borrow": "ödünç almak", "loans": "krediler", "victims": "kurbanlar" },
    questions: [ {q:"Did Simon Leviev use a dating app to meet women?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he say he was a diamond billionaire's son?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he take women on private airplanes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he send scary pictures of his bodyguard?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the women he could use his credit cards?", a_en:"No", a_tr:"Hayır"}, {q:"Did the women take out bank loans to help him?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he in prison right now?", a_en:"No", a_tr:"Hayır"} ]
}];lessonData["11_CassieChadwick.mp3"] = [{
    text: "11. Cassie Chadwick. Cassie Chadwick was an expert at tricking banks and stealing their money. In the late 1800s, Andrew Carnegie was one of the richest and most famous men in the world. Cassie created a very clever and simple plan. She made a fake paper saying she was Andrew Carnegie's secret daughter. She also made fake papers saying Carnegie gave her millions of dollars to keep her quiet. She showed these papers to many bank managers in America. In those days, bankers did not want to bother a famous, rich, and powerful man like Carnegie to ask if the story was true. They just believed Cassie's lies. The banks gladly gave her huge loans. She bought sparkling diamonds, beautiful expensive clothes, and heavy gold necklaces. She stole about two million dollars, which is like sixty million dollars today. She lived like a true queen for many years. Eventually, a brave bank manager finally asked Andrew Carnegie about her. He said he did not know her at all. The police arrested her, and she died in prison a few years later.",
    dict: { "expert": "uzman", "tricking": "kandırmak", "clever": "zeki", "secret": "gizli", "bother": "rahatsız etmek", "gladly": "memnuniyetle", "sparkling": "parıldayan", "necklaces": "kolyeler", "queen": "kraliçe", "brave": "cesur" },
    questions: [ {q:"Was Cassie an expert at tricking banks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she say she was Andrew Carnegie's daughter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bank managers ask Carnegie if it was true?", a_en:"No", a_tr:"Hayır"}, {q:"Did the banks give her huge loans?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she buy sparkling diamonds?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Andrew Carnegie know her?", a_en:"No", a_tr:"Hayır"}, {q:"Did she die in prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_BillyMcFarland.mp3"] = [{
    text: "12. Billy McFarland. Billy McFarland promised to throw the best and most expensive music party in the world, but he created a huge disaster. He organized the famous Fyre Festival in the year 2017. He paid beautiful models to post amazing pictures of a sunny island in the Bahamas on Instagram. He promised luxury beach tents, amazing expensive food, and the best music bands in the world. Rich young people paid thousands of dollars for the tickets. But McFarland did not know how to organize a real festival, and he quickly ran out of money. He lied to everyone. When the excited guests arrived on the island, there were no luxury tents. They had to sleep in wet, dirty emergency tents. There was no good food, just simple cold cheese sandwiches in cheap boxes. The famous music bands did not come. It was a complete disaster, and people were trapped on the island with no flights home. The police arrested McFarland for fraud. A judge sent him to prison for four years because he stole money and lied to thousands of people.",
    dict: { "promised": "söz verdi", "disaster": "felaket", "organized": "organize etti", "models": "modeller", "tents": "çadırlar", "ran out": "tükendi/bitti", "excited": "heyecanlı", "emergency": "acil durum", "trapped": "mahsur kalmış", "fraud": "dolandırıcılık" },
    questions: [ {q:"Did Billy promise to throw an expensive music party?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he organize the Fyre Festival?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pay models to post pictures?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he run out of money quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Were there luxury tents when the guests arrived?", a_en:"No", a_tr:"Hayır"}, {q:"Did the famous music bands come?", a_en:"No", a_tr:"Hayır"}, {q:"Was he arrested for fraud?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_WilhelmVoigt.mp3"] = [{
    text: "13. Wilhelm Voigt. Wilhelm Voigt was a poor, old shoemaker in Germany in the year 1906. He had been in prison before and could not find a good job. He realized that the German people respected military uniforms too much and always followed orders. So, he slowly bought parts of a captain's uniform from different second-hand shops. He put the old uniform on and walked proudly down the street. He saw a group of real, tired soldiers and commanded them to follow him. Because he was wearing a captain's uniform, they obeyed without asking questions! He marched them to the local town hall. He told the mayor he was under arrest for a secret crime. Then, he confidently took all the money from the town's safe. He told the soldiers to guard the mayor, and he just walked away with the cash! When the police finally caught him, the story was in all the newspapers. Even the German Emperor laughed loudly at his clever trick. The emperor actually pardoned him early because the joke was so funny to the entire country.",
    dict: { "shoemaker": "ayakkabıcı", "respected": "saygı duyulan", "uniforms": "üniformalar", "second-hand": "ikinci el", "proudly": "gururla", "commanded": "emretti", "obeyed": "itaat etti", "marched": "yürüttü", "mayor": "belediye başkanı", "safe": "kasa", "pardoned": "affetti" },
    questions: [ {q:"Was Wilhelm Voigt a poor shoemaker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did German people respect military uniforms?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he buy a real, new captain's uniform?", a_en:"No", a_tr:"Hayır"}, {q:"Did he command a group of real soldiers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they obey him without asking questions?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he take money from the town's safe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Emperor pardon him early?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_JeanneDeValois.mp3"] = [{
    text: "14. Jeanne de Valois-Saint-Remy. Jeanne was a poor woman who lived in France in the 1780s. She wanted to be very rich and live a luxury life in the royal court. She heard about a very expensive diamond necklace that the Queen, Marie Antoinette, did not want to buy. Jeanne created a brilliant and evil plan to steal it. She told a rich Cardinal that she was the Queen's secret best friend. She told him the Queen wanted the necklace secretly, but could not buy it herself. Jeanne even hired a poor woman who looked exactly like the Queen to meet the Cardinal in a dark garden at night. The Cardinal completely believed the clever trick. He bought the beautiful necklace and gave it to Jeanne. Jeanne's husband took the necklace to London and sold the diamonds for a lot of cash. When the Cardinal finally asked the Queen for the money, the terrible secret was discovered. The police arrested Jeanne, but the people hated the Queen so much that this huge scandal actually helped start the famous and bloody French Revolution!",
    dict: { "royal court": "kraliyet sarayı", "necklace": "kolye", "brilliant": "harika/zekice", "evil": "kötü/şeytani", "hired": "kiraladı", "exactly": "tam olarak", "discovered": "keşfedildi", "scandal": "skandal", "bloody": "kanlı", "revolution": "devrim" },
    questions: [ {q:"Was Jeanne a rich woman at first?", a_en:"No", a_tr:"Hayır"}, {q:"Did she want an expensive diamond necklace?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she tell a Cardinal she was the Queen's best friend?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she hire a woman who looked like the Queen?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Cardinal believe the trick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her husband sell the diamonds in London?", a_en:"Yes", a_tr:"Evet"}, {q:"Did this scandal help start the French Revolution?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_ArthurFerguson.mp3"] = [{
    text: "15. Arthur Ferguson. Arthur Ferguson was a Scottish actor who used his amazing acting skills to become a great swindler. After the First World War, many rich American tourists visited London to see the sights. Ferguson would stand in Trafalgar Square and look for wealthy tourists. He would pretend to be a very important and serious government worker. He told the American tourists that the British government was very poor after the long war. He said they were secretly selling famous public monuments to save the country from ruin. Amazingly, he 'sold' the famous Nelson's Column monument to an American for a lot of money. Later, he 'sold' Big Ben, the famous clock tower, to another tourist. He even took a huge cash down payment for Buckingham Palace! He was so confident that nobody suspected him. Later in his life, he moved to America and tried to sell the famous White House to a rich farmer. He was finally arrested by the police and went to prison for his crimes. He proved that a good actor can make people believe almost anything.",
    dict: { "actor": "aktör/oyuncu", "swindler": "dolandırıcı", "sights": "görülecek yerler", "wealthy": "zengin", "pretend": "gibi davranmak", "secretly": "gizlice", "monument": "anıt", "ruin": "yıkım/harabe", "down payment": "peşinat", "suspected": "şüphelendi" },
    questions: [ {q:"Was Arthur Ferguson a Scottish actor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pretend to be a government worker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell tourists the government was poor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he 'sell' Nelson's Column to an American?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he take a down payment for Buckingham Palace?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people suspect him easily?", a_en:"No", a_tr:"Hayır"}, {q:"Did he go to prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_LouPearlman.mp3"] = [{
    text: "16. Lou Pearlman. Lou Pearlman was very famous in the 1990s for creating big pop music groups like the Backstreet Boys and NSYNC. He seemed like a very successful, happy, and rich music manager. He bought huge houses, expensive cars, and flew around the world in private airplanes. But he had a very dark and greedy secret. First, he stole almost all the money from his young music stars. He made them sign very bad and unfair contracts when they were just teenagers. Second, he was running a massive Ponzi scheme behind the scenes. He created completely fake companies and fake banks. He asked regular people to invest in his businesses, promising they would make a lot of money very quickly. He stole about three hundred million dollars from his friends, his family, and normal people. When the police finally investigated his fake companies, he ran away to hide in Indonesia. The FBI caught him, and a judge gave him a twenty-five-year sentence. He died alone in prison, far away from the bright lights and the loud music of his famous past.",
    dict: { "manager": "yönetici/menajer", "greedy": "açgözlü", "unfair": "adaletsiz", "contracts": "sözleşmeler", "behind the scenes": "perde arkasında", "regular": "sıradan", "investigated": "araştırdı", "sentence": "hapis cezası", "alone": "yalnız" },
    questions: [ {q:"Did Lou Pearlman create big pop music groups?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he steal money from his young music stars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make them sign unfair contracts?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he running a massive Ponzi scheme?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he steal three hundred million dollars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hide in Indonesia?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die surrounded by his friends?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["17_EduardoDeValfierno.mp3"] = [{
    text: "17. Eduardo de Valfierno. Eduardo de Valfierno is famous for a crime that might be a myth, but it is a great and clever story. He liked to call himself a wealthy Marquis. In the year 1911, the famous Mona Lisa painting was stolen from the Louvre museum in Paris. A quiet man named Vincenzo Peruggia actually stole it. But years later, Valfierno told a reporter that he was the real mastermind. Valfierno said he never wanted to sell the real painting. Before the big theft, he paid an excellent artist to paint six perfect copies of the Mona Lisa. When the real painting was stolen, the news was in all the global newspapers. Valfierno then secretly met six different rich buyers. He sold his six fake paintings to them for a huge amount of money. He told each buyer they were getting the real stolen painting! He made millions of dollars and let the real thief take all the blame and go to prison. It was a perfect crime because the rich buyers could never tell the police they bought stolen art.",
    dict: { "myth": "efsane/mit", "wealthy": "zengin", "stolen": "çalınmış", "mastermind": "deha/planlayıcı", "copies": "kopyalar", "secretly": "gizlice", "fake": "sahte", "blame": "suç", "perfect": "mükemmel" },
    questions: [ {q:"Did Valfierno call himself a wealthy Marquis?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the real Mona Lisa stolen in 1911?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Valfierno steal the painting himself?", a_en:"No", a_tr:"Hayır"}, {q:"Did he pay an artist to paint six copies?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell the fake paintings to rich buyers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he let the real thief take all the blame?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the buyers tell the police?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["18_EnricMarco.mp3"] = [{
    text: "18. Enric Marco. Enric Marco was a man from Spain who told a terrible and sad lie just to get attention and respect. For many years, he was the president of a large group for Holocaust survivors in Spain. He gave hundreds of emotional speeches to schools, teachers, and politicians. He cried real tears as he told sad stories about his difficult time in a Nazi concentration camp called Flossenbürg during World War II. People thought he was a great and brave hero. He even received a special gold medal from the Spanish government. But in the year 2005, a smart historian looked at the real documents from the war. The historian discovered a shocking truth. Marco was never in a concentration camp at all! He actually went to Germany as a normal, volunteer worker, not a prisoner. He made up the entire sad story just because he wanted people to admire him and listen to him. He had to give his special medal back, and he lived the rest of his life in great shame because of his terrible lies.",
    dict: { "attention": "ilgi", "respect": "saygı", "survivors": "hayatta kalanlar", "emotional": "duygusal", "speeches": "konuşmalar", "concentration camp": "toplama kampı", "brave": "cesur", "hero": "kahraman", "historian": "tarihçi", "volunteer": "gönüllü", "shame": "utanç" },
    questions: [ {q:"Did Enric Marco tell a sad lie to get attention?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the president of a group for Holocaust survivors?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he receive a special gold medal?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he really in a concentration camp?", a_en:"No", a_tr:"Hayır"}, {q:"Did a historian discover the shocking truth?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he just a volunteer worker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have to give his medal back?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_ChristopheRocancourt.mp3"] = [{
    text: "19. Christophe Rocancourt. Christophe Rocancourt was a poor boy from a small town in France, but he became a master of fake identities. In the 1990s, he moved to Los Angeles in America. He wanted to be a part of the rich and famous Hollywood lifestyle. So, he told people he was a young member of the famous and wealthy Rockefeller family. He wore very expensive suits, drank the best wine, and drove incredibly fast cars. He was very charming and quickly became friends with famous movie stars and rich businessmen. He told his new rich friends that he could double their money if they invested in his secret businesses. Of course, there were no real businesses at all. He just took their money to pay for his own luxury life. He stole millions of dollars from people who thought he was a genius. The police finally caught him hiding in Canada. He went to prison, but later he wrote a popular book about his amazing crimes. He actually became quite famous in France for being such a clever thief.",
    dict: { "identities": "kimlikler", "lifestyle": "yaşam tarzı", "member": "üye", "wealthy": "zengin", "charming": "çekici", "double": "ikiye katlamak", "invested": "yatırım yaptı", "luxury": "lüks", "genius": "dahi" },
    questions: [ {q:"Was Christophe Rocancourt a master of fake identities?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Los Angeles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell people he was a Rockefeller?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wear very expensive suits?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he say he could double their money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have real secret businesses?", a_en:"No", a_tr:"Hayır"}, {q:"Did he write a popular book later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_SoapySmith.mp3"] = [{
    text: "20. Soapy Smith. Soapy Smith was a famous and very clever con man in the American 'Wild West' in the 1800s. His real name was Jefferson Randolph Smith. He got his funny nickname 'Soapy' because of his favorite street trick. He stood on the dirty street with a large crowd watching him. He wrapped regular, cheap bars of soap with paper. But he let the crowd clearly see him wrap a few bars with one hundred dollar bills. He mixed all the soap together in a bag and sold them for one dollar each. Poor people bought the soap, hoping to get the big money. But Smith used very fast magic tricks. He secretly took the money out, or he let his secret friends in the crowd buy the winning soap. The regular people only got normal soap. Later in his life, he moved to Alaska during the famous Gold Rush. He controlled a whole town with his large criminal gang. He ran fake telegraph offices and rigged card games until he was finally killed in a famous gunfight on the docks.",
    dict: { "nickname": "takma ad", "wrapped": "sardı", "cheap": "ucuz", "soap": "sabun", "bills": "banknotlar", "mixed": "karıştırdı", "hoping": "umararak", "magic tricks": "sihirbazlık numaraları", "rigged": "hileli", "gunfight": "silahlı çatışma" },
    questions: [ {q:"Was Soapy Smith a con man in the Wild West?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wrap cheap soap with paper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he let the crowd see him wrap hundred dollar bills?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he mix all the soap in a bag?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the poor people get the big money?", a_en:"No", a_tr:"Hayır"}, {q:"Did he move to Alaska during the Gold Rush?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he killed in a gunfight?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_Natwarlal.mp3"] = [{
    text: "21. Natwarlal. Natwarlal was India's most famous and clever con man. He was originally a smart lawyer, but he realized he was very good at copying other people's handwriting and signatures. He used this special skill to steal a lot of money from big banks and rich businesses. He was a master of disguise and changed his clothes and his face often to escape the police. But his most famous and funny crimes were selling public monuments to foreigners. He pretended to be an important government official. He found rich foreign tourists and 'sold' them the beautiful Taj Mahal! He actually did this three different times. He also successfully sold the huge Red Fort and the very important Indian Parliament building. He was arrested many times and judges gave him a total of one hundred and thirteen years in prison. But he was an expert at escaping from guards. He escaped from prison nine different times. The last time he escaped, he was eighty-four years old and sitting in a wheelchair! No one ever saw him again.",
    dict: { "handwriting": "el yazısı", "signatures": "imzalar", "skill": "yetenek", "disguise": "kılık değiştirme", "escape": "kaçmak", "foreigners": "yabancılar", "pretended": "gibi davrandı", "monuments": "anıtlar", "wheelchair": "tekerlekli sandalye" },
    questions: [ {q:"Was Natwarlal originally a lawyer?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he good at copying signatures?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he change his clothes and face often?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he 'sell' the Taj Mahal three times?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he an expert at escaping from guards?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he escape from prison nine times?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sitting in a wheelchair the last time he escaped?", a_en:"Yes", a_tr:"Evet"} ]
}];
